FROM postgres:latest

# Переменные окружения для настройки PostgreSQL
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
ENV POSTGRES_DB library

# SQL скрипт инициализации базы данных
COPY ./init.sql /docker-entrypoint-initdb.d/